### ISSUE TITLE
Error: Invalid value for 'DATA': '/home/xyz/secure/test': Permission denied

### ISSUE THREAD

**Issue by klack** [boukendesho/ykman-snap#1]
Eveyrthing appears to be working, except when I try to import an object per VeraCrypt's instructions.

```
klack@suprim:~$ sudo ykman piv objects import 0x5fc109 ~/secure/test
Error: Invalid value for 'DATA': '/home/klack/secure/test': Permission denied
```

I've opened permissions to 777 on this file and still get the same error.
Using the offical PPA package does not exhibit this error.
I believe there is a snap permission that needs to be set and I don't know what it is.

**Comment by boukendesho** [comment]
Yeah , it's a snap permission problem. 
Sorry since i dont use PIV so i didn't realized that ykman need to read some file from home directory.
Please try sudo snap refresh ykman --edge , use edge channel version that have the home r/w permission.
