### ISSUE TITLE
ERROR: Unknown format code 'b' for object of type 'str'

### ISSUE THREAD

**Issue by sebastian-zero** [boukendesho/ykman-snap#2]
Description:
"ykman info" command results in error "ERROR: Unknown format code 'b' for object of type 'str'"

```
$ ykman info
Device type: YubiKey 5 NFC
Serial number: xxxxxxxx
Firmware version: 5.2.4
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled

ERROR: Unknown format code 'b' for object of type 'str'
```

Environment:

```
$ uname -a
Linux sbtpkub 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ ykman --version
YubiKey Manager (ykman) version: 5.5.0

$ snap list | grep ykman
ykman                        5.5.0                       9      latest/stable    aoilinux        -
```

**Comment by boukendesho** [comment]
Thank you for report problems.

Revert to version 5.4.0 now for stable channel.

Will look into it.

**Comment by boukendesho** [comment]
Seems like a upstream problem, i've tested on ubuntu 22.04 vm and encountered same results through upstream PPA.

Already filed a issue in upstream repo.

**Comment by boukendesho** [comment]
https://github.com/Yubico/yubikey-manager/issues/619#issuecomment-2199528455

Confirmed by upstream. Waitting for fix.

**Comment by boukendesho** [comment]
Version 5.5.1 fixed.
